---
- name: Configure FRRouting devices
  hosts: routers
  gather_facts: no
  tasks:
    - name: Configure OSPF on routers
      ansible.builtin.shell: |
        vtysh -c 'configure terminal' \
              -c 'router ospf' \
              -c 'network 172.20.20.0/24 area 0' \
              -c 'exit' \
              -c 'exit' \
              -c 'write'

    - name: Configure interface descriptions in FRR
      ansible.builtin.shell: |
        vtysh -c 'configure terminal' \
              -c 'interface eth1' \
              -c 'description Connection to switch' \
              -c 'exit' \
              -c 'exit' \
              -c 'write'

    - name: Configure IP addresses using Linux commands
      ansible.builtin.shell: |
        ip addr add {{ router_ip }}/24 dev eth1 || true
        ip link set eth1 up
      vars:
        router_ip: "{{ '10.1.1.1' if 'r1' in ansible_host else '10.1.2.1' }}"

- name: Configure host networking (fixed for Alpine)
  hosts: hosts
  gather_facts: no
  tasks:
    - name: Set up basic networking on hosts (using raw for Alpine)
      ansible.builtin.raw: |
        ip addr add {{ host_ip }}/24 dev eth1 2>/dev/null || echo "IP may already exist"
        ip link set eth1 up 2>/dev/null || echo "Interface may already be up"
        echo "Host {{ ansible_host }} configured with {{ host_ip }}"
      vars:
        host_ip: "{{ '10.1.100.1' if 'host1' in ansible_host else '10.1.100.2' }}"
